#!/bin/bash
set -e
PKGID="$(cargo pkgid)"
[ -z "$PKGID" ] && exit 1
ORIGIN="${PKGID%#*}"
ORIGIN="${ORIGIN:7}"
PKGNAMEVER="${PKGID#*#}"
PKGNAME="${PKGNAMEVER%:*}"
shift
rm -rf $ORIGIN/target/debug
cargo test --no-run
rm -rf $ORIGIN/target/cov
for exe in $ORIGIN/target/debug/$PKGNAME-* $ORIGIN/target/debug/lib-*; do
    kcov $ORIGIN/target/cov $exe "$@"
done
