#!/bin/bash
# EXTRACT
# from http://tldp.org/LDP/abs/html/sample-bashrc.html
# modified by untitaker

if [ -f $1 ] ; then
     (case $1 in
         *.bz2)   bunzip2 $1      ;;
         *.gz)    gunzip $1       ;;
         *.rar)   unrar x $1      ;;
         *.zip)   unzip $1        ;;
         *.Z)     uncompress $1   ;;
         *.7z)    7z x $1         ;;
         *)       tar xfv $1 ;; # just hope for the best
       esac) 2>/dev/null || (echo "'$1' can't be unextracted." && exit 1)
 else
     echo "'$1' is not a valid file"
     exit 1
 fi
