#!/bin/bash

if [ -z "$1" ]; then
    sort=sort
    which gsort &> /dev/null && sort=gsort
    git reflog --format='%D' | cut -d, -f2 | rg -v '(^$|^tag:|^origin/|.*->.*)' | $sort -u | head -100 | fzf | xargs git checkout
    
elif [[ $1 = https://* ]]; then
    gh pr checkout "$@"
else
    git checkout "$@"
fi
