#!/bin/bash

if [ -z "$1" ]; then

    git reflog --format='%D' | cut -d, -f2 | while read line; do
        if [ -z "$line" ] || [[ $line == tag:* ]] || [[ $line == origin/* ]]; then
            continue
        else
            echo "$line"
        fi
    done | uniq | head -100 | fzf | xargs git checkout
    
else
    git checkout "$@"
fi
