#!/bin/sh

USAGE_HELP="Usage: $0 COMMAND
Commands:
    index:      Rewrite/create the index.
    mutt-query: Execute a mutt query.
    add:        Take mail from stdin, add sender to contacts. Print filename.
    add-edit:   Same as add, but open file in \$EDITOR afterwards. If the file
                is cleared, the contact is removed.

Environment variables:
    MATES_DIR: Path to vdir collection.
    MATES_INDEX: Path to index file.
    MATES_GREP: Optional, grep binary to use."


err() {
    local msg="$1"
    [ -n "$msg" ] && echo "$msg"
    exit 1
}


main() {
    [ -n "$MATES_DIR" ] || err "You need to set MATES_DIR"
    [ -n "$MATES_INDEX" ] || err "You need to set MATES_INDEX"
    [ -n "$MATES_GREP" ] || MATES_GREP='grep -i'
    cmd="$1"
    shift

    case "$cmd" in
        index)       command_index ;;
        mutt-query)  command_mutt_query "$@" ;;
        add)         command_add "$@" ;;
        add-edit)    command_add_edit "$@" ;;
        *)           command_help ;;
    esac
}

get_index() {
    find "$MATES_DIR" -mindepth 1 -name "*.vcf" | while read fname; do
        local name="$($MATES_GREP '^FN:' "$fname" | cut -d ':' -f '2-' | head -1)"
        local emails="$($MATES_GREP '^EMAIL' "$fname" | cut -d ':' -f '2-')"
        for email in $emails; do
            printf "%s <%s>\n" "$name" "$email"
        done
    done
}

command_index() {
    get_index > "$MATES_INDEX"
}


add_contact() {
    local header="$($MATES_GREP "^From:" | sed -e 's/^From: //')"
    local email="$(echo "$header" | sed -e 's/[^<]*<\(.*\)>/\1/')"
    local name="$(echo "$header" | sed -e 's/ *<[^>]*> *//')"

    while [ -z "$uid" ] || [ -f "$filename" ]; do
        local uid="$(uuidgen)"
        local filename="$MATES_DIR/${uid}.vcf"
        local tmpname="$MATES_DIR/${uid}.tmp"
    done

    echo "BEGIN:VCARD
VERSION:3.0
FN:$name
EMAIL:$email
UID:$uid
END:VCARD" > "$tmpname"
    mv -n "$tmpname" "$filename"
    echo "$filename"
}


command_add() {
    add_contact
    command_index
}


command_add_edit() {
    local filename="$(add_contact)"
    # http://unix.stackexchange.com/a/77593
    sh -c '$EDITOR -- "$@" <$0' /dev/tty "$filename"
    if [ -z "$(cat $filename)" ]; then
        rm $filename
        err "Contact not saved."
    else
        command_index
    fi
}


command_mutt_query() {
    if [ -z "$1" ]; then
        cat "$MATES_INDEX"
    else
        $MATES_GREP "$1" "$MATES_INDEX"
    fi
}

command_help() {
    err "$USAGE_HELP"
}

main "$@"
