#!/usr/bin/env python3
import os

def main():
    import sys
    import netrc
    n = netrc.netrc()
    user, machine = sys.argv[1], sys.argv[2]

    login, account, password = n.authenticators(machine)

    if login == user:
        print(password)
    else:
        sys.exit(1)

if __name__ == '__main__':
    main()
