#!/bin/sh
set -e

_is_dirty() {
    (! git diff-index --quiet HEAD) ||
        [[ $(git status --porcelain | tail -n1) != "" ]]
}

(
    echo "Initial sync"
    while true; do
        inotifywait -rq -e create -e delete -e move -t 300 \
            --exclude='(\.mbsyncstate)' \
        ~/.mail/*/ \
        || [ "$?" = "2" ]
        sleep 1
    done
) | while read line; do
    echo -e "$C_RED$line$C_RESET"
    mbsync -a
    notmuch new
    cd ~/.mail/
    echo .notmuch > .gitignore
    echo .mbsyncstate >> .gitignore
    echo .uidvalidity >> .gitignore
    git init -q
    git add -A
    git commit -m "$(date)" || ! _is_dirty

done
