#!/bin/sh
set -e

_is_dirty() {
    (! git diff-index --quiet HEAD) ||
        [[ $(git status --porcelain | tail -n1) != "" ]]
}

while true; do

    mbsync -a
    notmuch new
    cd ~/.mail/
    echo .notmuch > .gitignore
    echo .mbsyncstate >> .gitignore
    echo .uidvalidity >> .gitignore
    git init -q
    git add -A
    git commit -m "$(date)" || ! _is_dirty

    echo "Syncing in at most 5 minutes"
    inotifywait -rq -e create -e delete -e move -t 300 ~/.mail/ || [ "$?" = "2" ]
done
