#!/bin/sh
set -e
set -o pipefail

export MBSYNC_UBERSPACE_PASSWORD="$(pass www/webmail.draco.uberspace.de/login | head -1)"
[ -n "$MBSYNC_UBERSPACE_PASSWORD" ]

_is_dirty() {
    (! git diff-index --quiet HEAD) ||
        [[ $(git status --porcelain | tail -n1) != "" ]]
}

while true; do
    mbsync -a || true
    notmuch new
    cd ~/.mail/
    echo .notmuch > .gitignore
    echo .mbsyncstate >> .gitignore
    echo .uidvalidity >> .gitignore
    git init -q
    git add -A
    git commit -m "$(date)" || ! _is_dirty

    if [ "$1" = "-o" ]; then
        exit
    fi

    echo -ne "$C_RED"
    inotifywait -rq -e create -e delete -e move -t 300 \
        --exclude='(\.mbsyncstate)' \
    ~/.mail/*/ \
    || ([ "$?" = "2" ] && echo "Timeout")
    echo -ne "$C_RESET"
done
