#!/bin/bash
if [ -t 1 ]; then
    C_BLUE="\e[0;34m"
    C_RESET="\e[0m"
else
    C_BLUE=
    C_RESET=
fi

docker_output="$(
docker container ls --format "{{.Names}}" -a | while read name; do
    docker port "$name" | while read portinfo; do
        echo "$name $portinfo"
    done
done
)"

if [ "`uname`" = Darwin ]; then
    netstat -anv | grep LISTEN | awk '{print $1; print $4; print $9}'
else
    netstat -ltpn | cut -d/ -f1 | grep LISTEN | awk '{print $1; print $4; print $7}'
fi | while read proto && read portinfo && read pid; do
    echo -n "$proto"
    echo -ne "\t"
    echo -n "$portinfo"
    echo -ne "\t"
    docker_info=$(set -o pipefail && echo "$docker_output" | grep "${portinfo/\*/0.0.0.0}" | awk '{print $1}' | sort -u)
    if [ -n "$docker_info" ]; then
        echo -ne "${C_BLUE}docker${C_RESET} $docker_info"
    elif [ "$pid" != - ]; then
        echo -n "   pid $pid $(ps -p "$pid" -o comm=)"
    else
        echo -n "     -"
    fi
    echo
done | column -t -s $'\t'
