#!/usr/bin/python2
from __future__ import print_function
import requests
import newspaper
import os
import sys
import subprocess
import time


def launch_feh():
    print('Launching feh')
    subprocess.check_call('feh --bg-fill --no-fehbg ~/.background', shell=True)


def is_direct_link(x):
    return any(y in x for y in (".jpg", ".jpeg", ".png") )

def get_wallpaper_url():
    r = requests.get("http://www.reddit.com/r/earthporn.json",
                     headers={'User-Agent':
                              'wallpaper script -- markus@unterwaditzer.net'})
    j = r.json()

    for x in j["data"]["children"]:
        try:
            url = x["data"]["url"]
            if x['data']['is_self']:
                continue
            print(url)
            if not is_direct_link(url):
                site = newspaper.Article(url)
                site.download()
                site.parse()

                # Use better image detector -- don't use first one, but largest
                # one.
                site.top_img = None
                site.set_reddit_top_img()

                url = site.top_image
            if url:
                yield url

        except Exception as e:
            print(e)
            continue


def main():
    launch_feh()
    for url in get_wallpaper_url():
        try:
            print('Downloading {}'.format(url))
            r = requests.get(url)
            r.raise_for_status()
        except Exception as e:
            print(e)
            continue
        else:
            break
    else:
        print('Nothing found!')
        sys.exit(1)

    with open(os.path.expanduser('~/.background'), 'wb+') as f:
        f.write(r.content)

    launch_feh()


def _main():
    for trial in range(1, 11):
        try:
            return main()
        except Exception as e:
            import traceback
            traceback.print_exc()
            print(e)
            print('Retrying in {} seconds'.format(trial))
            time.sleep(trial)


if __name__ == '__main__':
    _main()
