#!/bin/sh

# This is slightly better than `printf %q` because it avoids to escape
# whitespace as "\ ", which really is unreadable
selection="$(cat | sed -e "s/'/'\\\\''/g")"
tmux neww -n spacemod-vim
tmux send-keys -t spacemod-vim "spacemod '$selection' '$selection' $1"
