#!/bin/bash
dzen2_globalparams="-e '' -h 16 "

right() {
    (python -u $(which unti_kinky.py) | dzen2 -ta r -sa r $dzen2_globalparams) &> /tmp/kinky_log
}

left() {
    dzen2 -sa l -ta l -expand r $dzen2_globalparams
}

$@
