#!/bin/sh
cmd=""
[ "$DISPLAY" != "" ] && cmd="urxvt -e"
$cmd sh -c "tmux -q has-session && tmux attach-session -d || tmux new-session -n$USER -s$USER@$HOSTNAME"
if [ ! -z "$1" ]; then
    tmux neww "$1"
fi
