#!/bin/sh

if [ ! -z "$1" ]; then
    tmux neww "$1"
else
    if tmux -q has-session; then
        exec tmux attach-session -d
    else
        exec tmux new-session -n$USER -s$USER@$(echo $HOSTNAME | tr -d.)
    fi
fi
