#!/bin/sh
set -x

if [ "$HOSTNAME" != "untiserver" ]; then
    remote_flag="-r untiserver:"
    check_size() {
        ssh untiserver du -s /mnt/media/backups/bup/
    }
else
    remote_flag=""
    check_size() {
        du -s /mnt/media/backups/bup/
    }
fi

size_before="$(check_size)"
for folder in `cat ~/.backup-folders`; do
    echo -e $C_RED$folder$C_RESET
    bup index ~/$folder/
    bup save -n $HOSTNAME-$folder $remote_flag ~/$folder/
done


echo
echo "Before:"
echo "$size_before"
echo "After:"
check_size

