#!/bin/sh

# Wrapper around selecta with own customizations

CONTENT=""
LINES=0

while read line; do
    CONTENT+="$line"
    CONTENT+=$'\n'
    LINES=$[LINES + 1]
done

if [ $LINES == 0 ] || [ $LINES == 1 ]; then
    echo "$CONTENT"
else
    echo "$CONTENT" | selecta $@
fi
