#!/bin/sh
set -e
if [ "$1" = "baikal" ]; then
    pass www/home.unterwaditzer.net/baikal/login | head -1
elif [ "$1" = "nextcloud" ]; then
    pass www/nextcloud.unterwaditzer.net/login | head -1
elif [ "$1" = "remotestorage" ]; then
    cat ~/.vdirsyncer/remotestorage-token
else
    false
fi
