#!/bin/sh

PT=`env TZ=US/Pacific date`
CT=`env TZ=US/Central date`
AT=`env TZ=Australia/Melbourne date`

echo "San Francisco (Pacific) $PT"
echo "              (Central) $CT"
echo "Australia/Melbourne     $AT"
