#!/bin/bash
dzen2_globalparams="-e '' -h 16 "

right() {
    python -u ~/scripts/unti_kinky.py | dzen2 -ta r -sa r $dzen2_globalparams
}

left() {
    dzen2 -sa l -ta l -expand r $dzen2_globalparams
}

$@
