#!/bin/bash
# A script which spawns the offlineimap daemon and "daemonizes" w3watch

www2mail() {
    while true; do
        echo -e "\e[0;31m Updating w3watch...\e[0m"
        w3watch_text="$(w3watch -c)"
        if [ "$w3watch_text" ]; then
            echo -e "\e[0;31m Updates for w3watch!\e[0m"
            echo -e "Subject: w3watch updates \n\n $w3watch_text" > "~/.mail/uberspace-markus/INBOX/new/w3watch_$(date +%s)"
        else
            echo -e "\e[0;31m No updates for w3watch\e[0m"
        fi
        sleep 3600
    done
}

www2mail &
offlineimap &

wait
